name: linkedin-feed-capture
channels:
  - conda-forge
  - defaults
dependencies:
  # Python
  - python=3.11
  
  # Core Dependencies (flexible versions for conda compatibility)
  - selenium>=4.15.0
  - beautifulsoup4>=4.12.0
  - pydantic>=2.5.0
  - typer>=0.9.0
  - rich>=13.0.0
  - python-dotenv>=1.0.0
  - requests>=2.31.0
  - lxml>=4.9.0
  - tenacity>=8.0.0
  - structlog>=23.0.0
  - prometheus_client>=0.19.0
  - cryptography>=41.0.0
  
  # Testing Dependencies
  - pytest>=7.4.0
  - pytest-cov>=4.1.0
  - pytest-mock>=3.12.0
  - pytest-asyncio>=0.21.0
  - pytest-xdist>=3.5.0
  - coverage>=7.3.0
  
  # Development Tools
  - ruff>=0.1.0
  - black>=23.0.0
  - mypy>=1.8.0
  - pre-commit>=3.6.0
  
  # Additional Tools
  - ipython>=8.0.0
  - jupyter>=1.0.0
  - pandas>=2.0.0
  - numpy>=1.24.0
  
  # Pip dependencies (packages not available in conda or need specific versions)
  - pip
  - pip:
    - selenium-stealth==1.0.6
    - webdriver-manager==4.0.2
    - factory-boy==3.3.0
    - responses==0.24.0
    - freezegun==1.2.0
    - pytest-benchmark==4.0.0
    - memray==1.10.0
    - bandit==1.7.5
    - safety==2.3.5 